### ISSUE TITLE
Please add version to expyriment/__init__.py

### ISSUE THREAD

**Issue by berndf** [expyriment/expyriment#102]
Dear expyriment authors,

setup.py expects to find __version__!='' in __init__.py in releases, otherwise it tries to get version from git which fails in that case. However, __version__=='' in the github release zip/tar archives.

Thanks for expyriment and best regards,
Bernd

**Comment by fladd** [comment]
Dear Bernd,

we release Expyriment officially through PyPi. Please see http://docs.expyriment.org/Installation.html for detailed (online and offline) installation instructions.

The zip/tar archives on GitHub are the raw source of Expyriment. This is not supposed to be run directly. We have an automated build process to create a release from this source, in which, besides other things, the version and revision numbers of the current build will be put into the `__version__` and `__revision__`attributes, respectively. You actually can build your own release from the source code if you want to. For this, you will need to clone our git repository, though. You can then run `setup.py` yourself.

The reason you cannot build a release from the zip/tar archive (with our `setup.py`) is that this archive does not contain any information about the state of the code, such as the revision. If you built this code, and then asked us for support, we would not know which version of the code you are running, which would complicate giving support. We hence aim to guide users towards our official releases.

Please also note that, while we release in wheel format, you can always extract the official `.whl` file if you need the contents (e.g. for embedding in other applications).

**Comment by berndf** [comment]
Dear Florian,

well, in gentoo, being a source-based distribution, there usually is no such thing as "raw sources". There just are sources, and they are expected to compile/build without the involvement of additional scripts geared towards a special binary release system. Pulling releases through the release tarballs in github is a very common thing to do actually. Maybe there can be a fallback extracting the version string from the name of the directory, but it should not fail in any case - you could still just close bug reports by people unable to report the version they have as invalid, should they really grow into a problem ;-)
Best regards,
Bernd

**Comment by fladd** [comment]
Dear Bernd,

nothing is binary in the released Expyirment wheels. It is all pure Python. So when you unzip the `.whl` file, you get the source code for usage in Gentoo. If you call `setup.py` on this, it will install on your system.

So it is just a matter of unzipping a different file to obtain the source :-)

Best,
Florian

**Comment by berndf** [comment]
Dear Florian,
.whl is "A built-package format for Python." https://pypi.python.org/pypi/wheel. You'll learn the difference once you add a C module. Anyway, thanks for your work!
Best regards,
Bernd

**Comment by fladd** [comment]
I am aware of what a `.whl` file is, thank you :-)
But as I said, Expyriment has no compiled code, so there is no difference.
It seems a bit redundant to me, but we could repackage the .`whl` file into a `.tar` file (with the exact same contents!) and link this on the release page as "source", if this helps?

**Comment by berndf** [comment]
Thanks, no worries! It's just a principal distinction of stages - everything before "build" is source, afterwards it's binary distribution, no matter whether or not it would be possible (or even trivial as in this case) to extract some (or even all current) sources from the distribution file. setup.py is supposed to build and install the software to its installation path, and on gentoo this process is automated and recorded so that the system knows which files belong to that package. Works in 99% of all packages, even with the most complicated compiled modules, but there are always exceptions... An ebuild for gentoo can simply patch the source and/or setup.py, it would just be nicer if this wasn't necessary.

**Comment by fladd** [comment]
I think the confusion here is that our GitHub repository is not there to _distribute_ the Expyriment source, but merely to centrally _host_ it. Besides being open source, we decided to also develop publicly for transparency reasons, so that people can track our progress, and can easily participate. Hence, our GitHub repository is for developers, not end users. The code on there is not made for direct distribution or installation.

However, we agree that we should also officially distribute the source (independently of how we chose to develop) in a format that is known to end users. We will hence release the source as a tar ball in the future. You can then download this tar ball and run the `setup.py`, and it will work. No build process needed. We will release this officially on PyPi, so source distributions, such as Gentoo, will be able to pick up the source tar ball via `pip`, instead of the `.whl`.

For source code of the current ongoging development, you can call  `make tarball` (this requires cloning the source from GitHub).

I hope this clarifies everything?

**Comment by berndf** [comment]
Yes, that solution via pip works, thanks!

**Comment by fladd** [comment]
We now implemented a way to correctly install Expyriment from the downloadable GitHub source archives: https://github.com/expyriment/expyriment/pull/103.
