### ISSUE TITLE
Mouse wheel in TextMenu

### ISSUE THREAD

**Issue by lindemann09** [expyriment/expyriment#104]
Hallo Oliver,

mir ist noch etwas am TextMenu aufgefallen: Wenn man Scrolling zulässt, lässt sich die Liste, wie erwartet, mit dem Mausrad nach oben und unten scrollen. Allerdings gibt es ein Problem, wenn der Mauszeiger auf dem aktuell hervorgehobenen, grau markierten Feld ist. Dreht man auf dieser Position die Maustaste, wir der entsprechende Eintrag gewählt. Habe ich etwas übersehen?

Viele Grüße,
Sven

**Comment by fladd** [comment]
Google translate:

Hello Oliver,

I have noticed something else on the TextMenu: If you allow scrolling, the list can be scrolled up and down as expected with the mouse wheel. However, there is a problem when the mouse pointer is on the currently highlighted, gray-marked field. If you turn the Maustaste on this position, we select the corresponding entry. Have I overlooked something?

Best regards,
Sven
