### ISSUE TITLE
TextInput for non-english characters

### ISSUE THREAD

**Issue by RonKatz** [expyriment/expyriment#111]
io.TextInput

Having trouble typing in Hebrew characters in TextInput.
While typing, the input box stays empty and wouldn't register the text.

I've changed the encoding to utf-8, 
The editor's (PyCharm) encoding settings as well.
Tried changing the fonts, and tried the ascii filters.

Had success presenting Hebrew text in Stimuli.TextScreen, and in the TextInput message.
Also managed to read Hebrew text from text files.

**Comment by fladd** [comment]
Yes, we indeed limit the input to the first 256 characters of unicode by default. We need to change this. For now, you can overwrite this by setting the `ascii_filter` attribute when initializing a TextInput (or by overwriting `expyriment.io.defaults.textinput_ascii_filter`). The Hebrew unicode block extends from 1424 to 1535. So if you set it to 1535, it should work.

(Note to self: We should probably rename this to `unicode_filter` 😄)

**Comment by RonKatz** [comment]
Thank you very much for the quick response!

Sorry, but I didn't understand how to write it:
expyriment.io.defaults.textinput_ascii_filter =

**Comment by fladd** [comment]
There are two options:

1) When initializing the TextInput:
    ```
    t = expyriment.io.TextInput(message="Your input:", ascii_filter=list(range(1535)))
    ```

2) Via the defaults (in case you want it to affect several TextInput instances in your experiment):
    ```
    expyriment.io.defaults.textinput_ascii_filter = list(range(1535))
    t = expyriment.io.TextInput(message="Your input:")
    ```

Hope this helps.

Best,
Florian

**Comment by RonKatz** [comment]
works like a charm.

thanks a lot!

**Comment by fladd** [comment]
Glad I could help!
