### ISSUE TITLE
Present Text Input Right to Left

### ISSUE THREAD

**Issue by RonKatz** [expyriment/expyriment#112]
Hello,

Thanks to Florian's help, i've managed to present text in Hebrew in expyriment.io.TextInput.

My problem now is to present the text Right to Left, instead of Left to Right. 

Any ideas?

Regards,
Ron Katz

**Comment by fladd** [comment]
Hi Ron,

is there more to this than just reversing the string (e.g. `my_string[::-1]` or `"".join(reversed(my_string))`? 

(I have a feeling there is. Could you maybe elaborate on the exact issue you are having?)

**Comment by RonKatz** [comment]
Hi Florian,

I'm using TextInput to collect text in Hebrew from the user.
Thanks to your help, the Hebrew characters are now visible and can used as a string later on.
The problem is, that the text is presented from Left to Right, instead of from Right to Left as in Hebrew.
So for example, If you type in "רון", the user input presents "ןור".
But, when I add the string to a data file, it shows the word in the correct Right to Left order.

**Comment by fladd** [comment]
Oh you are talking about the `TextInput` of course, sorry. Yes, this is not possible at the moment. We need to implement an `rtl` parameter, than can be set to `True` and will then show input text from right-to-left. I will implement this for the next update (0.9.1).

**Comment by RonKatz** [comment]
Thanks for the response.

1. This attribute is critical for my experiment, so I think I'll try to write it myself. Any general ideas?

2. Do you have an estimation for the next update's release date?

**Comment by fladd** [comment]
Hi,

1. Should be straight forward. I would just reverse the string `self._user` here if the attribute is set: https://github.com/expyriment/expyriment/blob/master/expyriment/io/_textinput.py#L387

2. We are aiming to release 0.9.1 within the next month

**Comment by RonKatz** [comment]
Great!

Again, Thank you very much for your kindness.
