### ISSUE TITLE
Expyriment Position and Size System

### ISSUE THREAD

**Issue by RonKatz** [expyriment/expyriment#114]
Hello,

I'm Trying to create a task using text buttons.
For that, I'm creating stimuli.TextBox items, 
And plotting them on stimuli.BlankScreen.
I will measure response using exp.mouse.

I'm having trouble with the position and size of the items.
I didn't really understand the Expyriment position system.

My goal is to create the objects, so they can fit in different screens.
I tried using fractions of exp.screen.size, but it didn't work (object weren't visible).
 
I tried using misc.geometry.coordinates2position , but got an error:
"coordinates2position takes 1 positional argument but 2 were given".

any Ideas or explanations about positions and sizes?

Thanks.
Ron Katz

**Comment by lindemann09** [comment]
This is not a bug report! Please direct question and support requests about Experiment to user forum: http://forum.expyriment.org/
