### ISSUE TITLE
documentation site unaccessible

### ISSUE THREAD

**Issue by darrenchiu** [expyriment/expyriment#127]
Hi team, sorry to raise issues. But seems the documentation site `http://docs.expyriment.org/` is unaccessible, can anyone help take a look?

Thanks a lot! Also, thanks for creating this awesome framework for creating experiments!

**Comment by fladd** [comment]
Hi there,

we are aware of the issue. It is a result of moving to GitHub pages for hosting the website. It will hopefully soon be fixed.

**Comment by darrenchiu** [comment]
thanks a lot for the prompt reply! this library is indeed a very useful one...
