### ISSUE TITLE
misc.geometry.points2vertices() drifts when there are many points

### ISSUE THREAD

**Issue by smathot** [expyriment/expyriment#133]
The `point2vertices()` function calculates vertices by looking only at pairs of consecutive points. Because of this, rounding errors accumulate, potentially leading to substantial distortion of polygon shapes.

I noticed this when running the following script in OpenSesame, which draws a pieslice using a polygon. The more points there are in the polygon, the more the resulting shape is not actually a pieslice. The leftmost shape is based on 4 points, the middle on 101, and the rightmost on 201 points. The details of this particular test script don't really matter though: the problem clearly results from accumulating rounding errors in `points2vertices()`.

~~~ python
import numpy as np


def PieSlice(x, y, r, a1, a2, steps=200, **style_args):
	
	"""
	Creates a Polygon element in the shape of a piesliece, which can be added to
	a Canvas.
	
	arguments:
		x : center x coordinate (the sharp end of the slice)
		y : center y coordinate (the sharp end of the slice)
		r : the radius of the pieslice
		a1 : the starting angle in radians
		a2 : the ending angle in radians
		steps : the number of steps from a1 to a2.
	"""
	
	v = [ (x, y) ]
	for a in np.linspace(a1, a2, steps):
		v.append( [x + r*np.cos(a), y + r*np.sin(a) ] )	
	return Polygon(v, **style_args)
	
	
c = Canvas()
c.circle(-400, 0, 100, color='green', fill=True)
c['pie1'] = PieSlice(x=-400, y=0, r=100, a1=0, a2=.25*np.pi, steps=3, fill=True)

c.circle(0, 0, 100, color='green', fill=True)
c['pie2'] = PieSlice(x=0, y=0, r=100, a1=0, a2=.25*np.pi, steps=100, fill=True)

c.circle(400, 0, 100, color='green', fill=True)
c['pie3'] = PieSlice(x=400, y=0, r=100, a1=0, a2=.25*np.pi, steps=200, fill=True)

c.show()
~~~

![image](https://user-images.githubusercontent.com/594936/38471422-48a2cf72-3b71-11e8-8230-46a6b78cb90a.png)

**Comment by fladd** [comment]
@lindemann09 is this still happening?

**Comment by lindemann09** [comment]
points2vertices works correctly. It has been checked.

**Comment by fladd** [comment]
Great, then this issue can be closed.
