### ISSUE TITLE
data_preprocessing.Aggregator.__init__ doesn't work because it doesn't cast np's version number to int

### ISSUE THREAD

**Issue by cstenkamp** [expyriment/expyriment#145]
in the constructor of the Aggregator, defined at expyriment/misc/data_preprocessing.py, it gets the numpy-version-number as 
` _version = _np.version.version.split(".") `
(line 301). Then it compares this string with integers:
`        if not _version[0] == 1 and _version[1] < 6:`
. A simple cast solves this issue:
`        if not int(_version[0]) == 1 and int(_version[1]) < 6:`

**Comment by lindemann09** [comment]
Dear cstenkamp, 

thanks a lot for your feedback. That is indeed a bug.The bug has already been fixed in the new version. If you need a quick fix I suggest to install the Expyriment  0.9.1 beta https://github.com/expyriment/expyriment/releases/tag/v0.9.1b2 

Oliver
