### ISSUE TITLE
No file found in b'<directory name>'

### ISSUE THREAD

**Issue by chimpyTheDev** [expyriment/expyriment#149]
I tried reading a file using expyriment.misc.data_preprocessing and I got an error saying no data file found in a specific directory.
Upon further investigation I found that the error is raised by the reset function.
Is there a step I'm missing here?

**Comment by lindemann09** [comment]
Thanks you very much for your feedback. This is indeed a bug. I will have a closer look as soon as possible and fix it with the next release. Which Python version and which operation system do you use?

**Comment by chimpyTheDev** [comment]
At the time  I was using python 3.7 running on windows 10 pro.
