### ISSUE TITLE
Function needed?

### ISSUE THREAD

**Issue by lindemann09** [expyriment/expyriment#159]
https://github.com/expyriment/expyriment/blob/6b5c9b5346cf4d99ba989a96085bda4b63b40870/expyriment/_internals.py#L66

**Comment by lindemann09** [comment]
Why do we need this function?

**Comment by lindemann09** [comment]
OK, but that does not mean that we should call the function internally all the time. 

Moreover, the function is not documented and not visible for the user (`_internals`). It is anyway useless for experienced users and experienced user can call pygame directly. I suggest to kick  it out. https://github.com/expyriment/expyriment/pull/160

**Comment by fladd** [comment]
yeah, it all depends also on what we do next with the event queue anyway. Will have to check out Pygame 2 first, see how the queue is handled in SDL 2, and then decide what we do.
