### ISSUE TITLE
Lack of precision while waiting keyboard input?

### ISSUE THREAD

**Issue by thomas-vincent** [expyriment/expyriment#165]
https://github.com/expyriment/expyriment/blob/e3619ed5e2a7e4604a3cdd9152ebb886a28e92fa/expyriment/io/_keyboard.py#L308

This line introduces a non-negligible rounding error.
While one expects to wait no longer than the input duration, I see an imprecision of around 1 ms.
This is problematic when one wants to control the exact paradigm duration.

What am I missing?

**Comment by fladd** [comment]
You aren't missing anything, but apparently we did. The line you are referring to should probably be followed by a `continue` to not have the subsequent 0.5 m sleep evaluated. I guess we didn't catch this until now, because the inaccuracy of computer keyboards is usually much larger than that. Because of that it is always recommended to use dedicated button boxes (connected vie e.g. serial port) for accurate response timing.

But I will fix this in the next release. Thanks for reporting!

**Comment by thomas-vincent** [comment]
I completely agree about the usual high keyboard latency. Although this [kind of keyboard (latency < 1ms)](https://github.com/expyriment/expyriment/blob/e3619ed5e2a7e4604a3cdd9152ebb886a28e92fa/expyriment/io/_keyboard.py#L304) is used in some cognitive experiments.

The question is also what to expect when there is **no** input : we expect to wait exactly the amount of time given.

Maybe flooring could be removed there too:
https://github.com/expyriment/expyriment/blob/e3619ed5e2a7e4604a3cdd9152ebb886a28e92fa/expyriment/io/_keyboard.py#L304
https://github.com/expyriment/expyriment/blob/e3619ed5e2a7e4604a3cdd9152ebb886a28e92fa/expyriment/io/_keyboard.py#L300
https://github.com/expyriment/expyriment/blob/e3619ed5e2a7e4604a3cdd9152ebb886a28e92fa/expyriment/io/_keyboard.py#L288
https://github.com/expyriment/expyriment/blob/e3619ed5e2a7e4604a3cdd9152ebb886a28e92fa/expyriment/io/_keyboard.py#L282

In fact I don't get the rationale to always round to the nearest millisecond. The timing values should directly reflect the accuracy of the system clock and input. No?

**Comment by fladd** [comment]
I entirely agree. The decision to support up to millisecond accurate timing is historical. When we started with Expyriment over 10 years ago, this was the reasonable unit in which accuracy could be guaranteed for timing-critical things, given everything involved. In some tests I did recently, I realized that nowadays indeed, with OSs having better clocks, we can actually get an accurate timing with higher resolution. Hence, my plan for the next major release (v1.0.0) is to switch to microsecond timing by default.

I am curious to learn more about this keyboard you mentioned, btw.

**Comment by thomas-vincent** [comment]
I fixed the link for the keyboard: [https://www.empirisoft.com/directinkb.aspx](https://www.empirisoft.com/directinkb.aspx)

**Comment by fladd** [comment]
Thanks for the link. Very pricey! I guess we stick to Arduino-based custom button boxes for now :-)

**Comment by fladd** [comment]
fixed in master branch
