### ISSUE TITLE
Can't install expyriment : no "setup" file running "buildconfig/congif.py"

### ISSUE THREAD

**Issue by lagree-emmanuel** [expyriment/expyriment#168]
Hi there ! 
I tried to install expyriment following the instructions of the website, it looks like I miss dependencies, even though I installed everything was required on the website, and tried to install all the pacakages 'missing' in the error message (for instance I have portmidi installed, no matter what the error says). (I work on Fedora 33, and have PyGame and Anaconda installed)
I paste the error message : 

ERROR: Command errored out with exit status 1:
     command: /home/lagree_emmanuel/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-az1bq5q2/pygame/setup.py'"'"'; __file__='"'"'/tmp/pip-install-az1bq5q2/pygame/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-rtyzu3x1
         cwd: /tmp/pip-install-az1bq5q2/pygame/
    Complete output (18 lines):
    
    
    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using UNIX configuration...
    
    
    Hunting dependencies...
    SDL     : found 1.2.15
    FONT    : found
    IMAGE   : found
    MIXER   : found
    PNG     : found
    JPEG    : not found
    SCRAP   : found
    PORTMIDI: not found
    PORTTIME: not found
    FREETYPE: found 23.4.17
    Missing dependencies
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I don't really know at what level the error is. Do you have any ideas about how I should proceed ?
Sorry I am new, thanks for your help !

**Comment by fladd** [comment]
Hi there,

I have not seen this error before. Does this come from pip?
Could you give some more details on your system, like the exact Python and PyGame versions?
This could also be related to Anaconda (we only test on official Python). So maybe trying if you can reproduce the same error with the official Python might also be a good next step.

**Comment by chrplr** [comment]
For what it is worth (Ubuntu here)
I have installed expyriment with `pip install expyriment[all]` in an
Anaconda python 3 environnement.
I did not encounter any issues.

Chris
PS: Same thing under Windows, with anaconda python.

--
Christophe Pallier (http://www.pallier.org)
INSERM Cognitive Neuroimaging Lab (http://www.unicog.org)

**Comment by lagree-emmanuel** [comment]
Hi Florian,

Thank you for your answer !

I use Fedora 33, **pygame 2.0.1** (SDL 2.0.14, Python 3.8.5) (and they work very well). I have tried the installation with pip install indeed, both within the spyder shell and with the basic shell of the os/computer.

I have uninstalled anaconda and pygame and have tried to install expyriment via the main shell. 
It says that it downloads pygame 2.0.1 (automatically).  Then it cannot install expyriment because a version >= 1.9 but < 2.0 is required (there are conflicting dependencies, it says). It tries to use a cached pygame 1.9.6.tar.gz : when it does so, the same error as mentioned in my first post is displayed.

The problem is that it does not let me install pygame < 2 and I do not know how to do it. 

I guess it is the main problem, and it does not have much to do with anaconda...

Thanks for your time anyway, and sorry if my issues are naive !
Emmanuel

**Comment by fladd** [comment]
Currently, Expyriment does **not** support Pygame 2 and SDL2. Future versions will.

I am not familiar with Fedora, but you cannot install an older version of Pygame through the Fedora repositories? Maybe this helps: https://unix.stackexchange.com/questions/151689/how-can-i-instruct-yum-to-install-a-specific-version-of-package-x ?

Alternatively, you could install Python 3.7 and then use pip to install Pygame 1.9.6 (there are no Linux wheels for newer Python versions) with: `pip install pygame==1.9.6`

@chrplr In Ubuntu, did you install Pygame (1.9.6) before via apt-get?

**Comment by chrplr** [comment]
I have separate conda environments for pygame2 and for expyriment. I just
had to run 'pip install expyriment in a virgin environment and it installed
pygame 1.9.6as a eependency. Expyriment works well then, and I did not have
to force any install (nor to install any other package manually).



PS:Some of my students using MacOS have had to force the upgrade to pygame2
(wrong libs for pygame1.9), and have not encountered issues yet. The
backward compatibility or pygame2 is rather impressive. @Florian: can you
tell us in which subsystems of pygame we could expect problems?

**Comment by chrplr** [comment]
Maybe sdl1.2 and sdl2 were already installed (apt install)

**Comment by lagree-emmanuel** [comment]
Thank you for your answer ! I will try to figure it out !
Best

**Comment by fladd** [comment]
> @florian: can you tell us in which subsystems of pygame we could expect problems?

No particular one, we just haven't fully tested it yet. I tried to switch to a dev version of Pygame 2 a while ago, and there were still some issues, especially with the screen size. Those, however were rather obvious.

The original plan was to switch to Pygame 2 only in the 1.0 release, in which we also wanted to potentially look at some more larger changes (e.g. new audio system, sub-millisecond timing, HiDPI, multi touch support). However, if it turns out that backwards compatibility is really that good, and switching to Pygame 2 is easily possible, we might allow for it in 0.10.1 release already.
