### ISSUE TITLE
Calling `Canvas.copy()` clears the original canvas (???)

### ISSUE THREAD

**Issue by chrplr** [expyriment/expyriment#171]
When I create a copy of a Canvas (and do not even touch it), the original Canvas is cleared. 

More precisely, on my system (Ubuntu 20.04, Anaconda Python 3.7.9, Experiment 0.10.0, Dell precision 5530 with Intel graphics), the following code does not display anything iff the line 'c2= c.copy()' is executed. Looks like a bug (?) What about other systems? 

```python
import expyriment

exp = expyriment.design.Experiment(name="")

expyriment.control.initialize(exp)

stim = expyriment.stimuli.Picture('test.png')
c = expyriment.stimuli.Canvas((691, 1056), (0, 0))
stim.plot(c)

### comment or uncomment the following line and see the effect on diaply of 'c'
# c2 = c.copy()

expyriment.control.start()

c.present()
exp.clock.wait(2000)

expyriment.control.end()
```
![test](https://user-images.githubusercontent.com/1530674/111866967-4c56d180-8971-11eb-9765-e09e69c38c49.png)

**Comment by fladd** [comment]
Yes, confirmed. That is a bug. I will fix this for the next release, thanks!

**Comment by fladd** [comment]
As a workaround for now, this should work:

```
c_surface_copy = c._get_surface().copy()
c2 = c.copy()
c._surface = c_surface_copy
```

**Comment by lindemann09** [comment]
@fladd Can we close this issue?
