### ISSUE TITLE
Many characters are not captured by `expyriment.io.TextInput.get()`

### ISSUE THREAD

**Issue by cedricfoucault** [expyriment/expyriment#174]
**Steps to reproduce**
Execute the following expyriment script with python 3 from Terminal.
```
import expyriment

exp = expyriment.design.Experiment(name="TextInput Test")
expyriment.control.initialize(exp)
expyriment.control.start()
textinput = expyriment.io.TextInput("Try entering each character on your keyboard")
response = textinput.get()
```
When prompted, try entering each key on your keyboard and check if the corresponding character appears on screen.

**Expected Result**: The character appears on screen every time the key is pressed and is contained in the string returned by `.get()`.
**Actual Result**: For certain keys, the corresponding character never appears (and is not contained in the string returned by `.get()`), no matter how many times it's pressed. The keys that do not work seem to change randomly from run to run.

**Platform**
macOS 11.3.1 (Big Sur)
Python 3.7.4
expyriment 0.10.0
pygame 2.0.1 [(>= 2 required on macOS](https://www.pygame.org/wiki/GettingStarted#Mac%20installation))
PyOpenGL 3.1.5
future 0.18.2

**Comment by fladd** [comment]
To clarify: Is this with non-English characters? If so, have you tried to set the `character_filter` argument to a number high enough to include all characters on your keyboard? The default is to only include the first 256 unicode characters (plus the number keys): https://github.com/expyriment/expyriment/blob/master/expyriment/io/_textinput.py#L480.

**Comment by fladd** [comment]
I am afraid I cannot reproduce this. This might be related to Pygame2. Expyriment 0.10.0 does not officially support Pygame2.

**Comment by lindemann09** [comment]
Thanks @cedricfoucault for your bug report. The next release (v0.11) is coming soon and it will fix the issues.
