### ISSUE TITLE
sphinx issue

### ISSUE THREAD

**Issue by chrplr** [expyriment/expyriment#182]
When running "python setup.py install", I get the following error message
```
Running Sphinx v4.0.1
making output directory... done

Exception occurred:
  File "/home/neurostim/git/expyriment/documentation/sphinx/conf.py", line 156, in setup
    app.add_stylesheet("basic.css")
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'
```

Apparently, this function should be changed to `app.add_css_file()`

**Comment by fladd** [comment]
It appears that this was changed in a new Sphinx version. Thanks for reporting!

**Comment by chrplr** [comment]
A new deprecation warning appeared.

---
Running Sphinx v4.3.2
WARNING: while setting up extension conf.py: The app.add_stylesheet() is deprecated. Please use app.add_css_file() instead.
WARNING: while setting up extension sphinx_rtd_theme: 'html4_writer' is deprecated with sphinx_rtd_theme
---

---
conf.py
158:html4_writer = True
---

**Comment by fladd** [comment]
Let's see if this works now. Closing for now.
