### ISSUE TITLE
xpy_icon.png not found

### ISSUE THREAD

**Issue by chrplr** [expyriment/expyriment#202]
With a fresh install of expyriment from its source (`pip install .` from the github repo: `Expyriment 0.10.0+83.gf2b2ea1`), all scripts crash with the message

```{console}
File "/home/cp983411/anaconda3/envs/test-expy/lib/python3.10/site-packages/expyriment/io/_screen.py", line 101, in __init__
    icon = pygame.image.load(
FileNotFoundError: No such file or directory: '/home/cp983411/anaconda3/envs/test-expy/lib/python3.10/site-packages/expyriment/io/../xpy_icon.png'.
```

Looks like the splash file is now named `expyriment_logo.png`

**Comment by fladd** [comment]
Ah, forgot to put it into package_data. Should be fixed now: https://github.com/expyriment/expyriment/commit/3be6c41344e95e806f7e7da2bc9ecba05463e6de
