### ISSUE TITLE
how to perform online experiment with expyriment?

### ISSUE THREAD

**Issue by finch-f** [expyriment/expyriment#206]
Can expyriment work properly within a brower environment?

**Comment by fladd** [comment]
Being a Python library which also depends on several other packages, Expyriment does not run in a browser. While there are attempts of creating some form of Python interpreters within browsers (e.g. Brython, replit), these attempts unsurprisingly target mainly web development and its specific needs, and also put limits on the achievable timing accuracy.

I thing focusing on facilitating running Expyriment scripts on remote computers natively, with minimal intervention from the user, would be a more desirable goal, and it is something I am currently working on.
