### ISSUE TITLE
How to record participants' voices with expyriment?

### ISSUE THREAD

**Issue by finch-f** [expyriment/expyriment#207]
I want to record participants's speech output with expyriment. However, I do not know how to do this.

**Comment by chrplr** [comment]
One "cheap" way to achieve this is to use a sound recorder while expyriment
is presenting the stimuli; For example, if for a picture-naming experiment,
experyiment could play a short beep at the beginning of each trial, before
displaying a picture.
You can start and stop the sound recording program manually (or start it
from the Python expyriment script using `os.system()`).
Then, you will have a single, long wav file, where each trial is marked by
a beep, and you will be able to measure reaction times from these beeps
(using tools that automatically splice up sound files).


--
Christophe Pallier (http://www.pallier.org)
INSERM Cognitive Neuroimaging Lab (http://www.unicog.org)

**Comment by fladd** [comment]
There is not native way to do this with Expyriment currently. I am considering to add this in the future, though. Currently, I am doing it the same way as @chrplr describes.
