### ISSUE TITLE
Error Importing StimulationProtocol from from expyriment.design.extras

### ISSUE THREAD

**Issue by willstrawson** [expyriment/expyriment#208]
Hi,

I've inherited some scripts from another group using expyriment. I'm having issues importing StimulationProtocol:

`ImportError: cannot import name 'StimulationProtocol' from 'expyriment.design.extras' ([...]/env/lib/python3.7/site-packages/expyriment/design/extras/__init__.py)`

I've had a look inside the package directory and can't find any mention of StimulationProtocol apart from in `Changelog.rst.txt`, where it mentions that in version 0.8.0, the class was added: `new class: design.extras.StimulationProtocol`. However, it seems like it's been removed since then. I've tried importing version 0.8.0 but `ERROR: No matching distribution found for expyriment==0.8.0`.

I've also tried importing `expyriment[all]`, but the same error comes up. 

I also can't find any documentation for this class, so if there is any, it would be great to see that once this import issue is fixed.

Please advise :)

Thank you.

**Comment by fladd** [comment]
Hi there,

two questions to better pinpoint the issue:

1. Where there any errors when installing the extra plugins? (see https://docs.expyriment.org/Plugins.html#download-plugins-from-stash)
2. Where there any errors when importing the extras in your script? (see https://docs.expyriment.org/Plugins.html#usage)

**Comment by willstrawson** [comment]
Thank you for your help. I solved the issue now :)
