### ISSUE TITLE
How to generate a Gabor patch

### ISSUE THREAD

**Issue by itsdfish** [expyriment/expyriment#209]
Hi,

Thank you for putting together this helpful package. I hope it is OK to ask for help here.

 I would like to generate a Gabor patch. After looking through the documentation, and examples, I was unable to figure it out. Here is one of the things I tried:

```
import expyriment.stimuli.extras

expyriment.stimuli.extras.GaborPatch()
```

I received the following error:

module 'expyriment.stimuli.extras` has no attribute `GaborPatch`.

Any guidance would be greatly appreciated.

**Comment by itsdfish** [comment]
Thank you for your reply. I do not see a list of stimuli objects. It is blank. 

I used `pip install -U expyriment[all]` to install. Is it possible that the extra stimuli were not installed?

**Comment by lindemann09** [comment]
You should try to download  the extras once again from the stash via: 

```expyriment.misc.download_from_stash(content="extras")```

**Comment by itsdfish** [comment]
Thank you so much. That fixed the problem. 

I was wondering if you might be able to provide some guidance on a related question. I am interested in using a 2D array representation of the Gabor patch in a model. I was able to obtain a 2D array, but when I transformed it to an image for visual inspection, it was not correct. Do you have an approach you recommend? 

Thank you.


**Code **

```
import expyriment.stimuli.extras
from expyriment import design, control, stimuli
import numpy as np
from PIL import Image

patch = expyriment.stimuli.extras.GaborPatch()

patch_pixels = np.array(patch.get_pixel_array())

img = Image.fromarray(patch_pixels, mode = 'L')

img.show()
```

**Comment by itsdfish** [comment]
This is the best solution I found. Is there a better one?


```
import expyriment.stimuli.extras
import numpy as np
from PIL import Image

def convert_to_grayscale(image):
  # Check that the input is a 3D array
  if len(image.shape) != 3:
    raise ValueError("Input is not a 3D array")

  # Convert the image to grayscale using the formula:
  # grayscale = 0.2989 * R + 0.5870 * G + 0.1140 * B
  # where R, G, and B are the values of the red, green, and blue channels respectively
  return 0.2989 * image[:,:,0] + 0.5870 * image[:,:,1] + 0.1140 * image[:,:,2] 

patch = expyriment.stimuli.extras.GaborPatch()


# get the 3D matrix representation
# array_3d = patch.get_surface_array() # not working
array_3d = patch.pixel_array

# convert to 2D grey scale matrix representation
array_2d = convert_to_grayscale(array_3d)
# convert to image
new_image = Image.fromarray(array_2d)
# show image to see if it works.
new_image.show()
```

**Comment by fladd** [comment]
Hi @itsdfish,

glad to hear you figured it out so quickly with the help of @chrplr!

Concerning your second question:
@lindemann09 wrote the GaborPatch plugin and might be able to better answer this.

(For future questions, it would be better to ask them in the discussion forum instead of the issue tracker, which is mainly for handling bugs. This will also give you more interaction with other users).

**Comment by itsdfish** [comment]
@fladd thanks for bringing the forum to my attention. I will ask my questions there in the future. 

The solution I have for my second question seems sufficient, but I would be interested in a better approach if one exists. 

I will defer to your judgment for closing this issue. I will note that the code for extra stimuli did not download automatically on two of my computers. If that is the intended behavior, it might be good to instruct users to use `expyriment.misc.download_from_stash(content="extras")` in the documentation for the extra stimuli. 

Thank you again everyone for your help.

**Comment by fladd** [comment]
No extra stimuli are downloaded automatically together with Expyriment. They are optional. We provide a collection of them in the [Expyriment Stash](https://github.com/expyriment/expyriment-stash) (such as the Gabor Patch one), and they can be easily downloaded via the [command line interface](https://docs.expyriment.org/Plugins.html#download-plugins-from-stash).
