### ISSUE TITLE
Occasional v-sync and timing problems with Expyriment

### ISSUE THREAD

**Issue by smathot** [expyriment/expyriment#3]
*This is not really a specific bug report, but more of a general issue that arises from time to time.*

I've had some reports of OpenSesame users that experienced issues with v-sync and temporal precision (i.e. no blocking flip) with the Expyriment-based back-end. I also experienced this myself a few times. It is fairly unpredictable when this happens, but when it does, it is consistent on that particular system.

Issues like this are bound to arise on certain configurations, of course. However, quite often, PsychoPy works fine on the same systems. This suggests that there is something that PsychoPy does differently and, presumably, better when it comes to controlling the display. The reverse does not appear to occur as much (i.e. if Expyriment works, then PsychoPy generally works as well).

My knowledge of OpenGL is too limited to say anything useful about a possible cause or solution. But it might be helpful to take a look at how PsychoPy implements its OpenGL functionality. Is there some option that PsychoPy enables and Expyriment does not, or something along those lines?

Cheers!
Sebastiaan

**Comment by fladd** [comment]
Given that we are close to release, I think I can close this issue. @smathot if you are still interested, we can send you a pre version during the next week or so.
