### ISSUE TITLE
Video documentation code seems not to be complete

### ISSUE THREAD

**Issue by fnielsen** [expyriment/expyriment#64]
The documentation for the video example seems not to be entirely complete. I have added a bit extract in the example https://github.com/expyriment/expyriment/blob/master/documentation/sphinx/Video.rst

    import expyriment
    from expyriment import control, design, stimuli
    
    video = stimuli.Video("test.mpeg")  # Create video object
    
    exp = design.Experiment("Test")
    control.initialize(exp)
    expyriment.control.stop_audiosystem()  # Stop audio system
    
    video.preload()  # Preload video
    video.present()  # Start video playback and present first frame
    video.wait_end() # Continuously present the next frame until video stops

**Comment by fnielsen** [comment]
Branch: https://github.com/fnielsen/expyriment/blob/videodoc/documentation/sphinx/Video.rst

**Comment by fnielsen** [comment]
I don't think https://github.com/expyriment/expyriment/commit/e7d9445a415ee779b07a8317e697fb280dd2187b is for #64 

I have made a PR https://github.com/expyriment/expyriment/pull/67

**Comment by fladd** [comment]
Thanks for the suggestion.

I will include the following example in the next release:

```

    from expyriment import control, stimuli


    exp = control.initialize()

    video = stimuli.Video("file.mpg")  # Create video object

    control.stop_audiosystem()  # Stop audio system
    video.preload()  # Preload video into memory

    video.present()  # Start video playback and present first frame
    video.wait_end()  # Continuously present the next frame until video stops

    video.unload()  # Unload the video from memory
    control.start_audiosystem()  # Optionally start audio system again
```
