### ISSUE TITLE
Second user cannot start expyriment due to permissions on /tmp/experiment_tmp

### ISSUE THREAD

**Issue by fnielsen** [expyriment/expyriment#65]
On a multiuser Linux system two users cannot use expyriment as the /tmp/expyriment (/tmp/expyriment_tmp) directory is used and this is set with permission for only one of the users.  https://github.com/expyriment/expyriment/blob/master/expyriment/stimuli/defaults.py

**Comment by lindemann09** [comment]
Thanks a lot for the bug report. I will care about it and make for every user a own tmp folder.
