### ISSUE TITLE
expyriment init hangs on pygame.sysfont.initsysfonts()

### ISSUE THREAD

**Issue by dschreij** [expyriment/expyriment#69]
When trying out v0.8.0 of expyriment on OSX El Captian, 
    
    pygame.sysfont.initsysfonts() 

blocks the program, in both the setup.py install function, as well as when doing 

    import expyriment

in the python interpreter. You can only exit with Ctrl-C
I have the current homebrew installed pygame (v1.9.2a)
Is this call really necessary for expyriment to function correctly? As there are other ways to scan the available system fonts and commenting the initsysfonts() line out doesn't seem to break anything.

**Comment by fladd** [comment]
Hi Daniel,

thanks for the report.
I think I had similar issues with Homebrew when I tried it. It was related to SDL if I remember correctly. Which version of SDL do you have? I actually never could get everything to work correctly with Homebrew (which is why we suggest MacPorts).

Could you maybe check whether everything works on your Mac when you follow our official installation instructions? Just to be sure that it is really Homebrew related.

**Comment by dschreij** [comment]
I have version 1.2.15 of SDL and version 2.0.11 of sdl_ttf. I am amazed you never got things to work with homebrew as it for me was so much simpler and faster than macports, when I tried that before. I can't try macports, but manually installing by using the wheel also causes a hangup on the initsysfonts() call.

**Comment by fladd** [comment]
When you say manually installing, you mean [this](http://docs.expyriment.org/Installation.OSX.html#manually-alternative)? Including the alternative Python and (most importantly) Pygame?

I am also quite surprised that you had no issues with Homebrew and Pygame before. I actually really wanted to document a way to use Homebrew to install Expyriment (even as the officially suggested way), but I always ran into troubles for some reason. How exactly did you install Pygame with Homebrew?

**Comment by dschreij** [comment]
Yes those are the instructions I followed for manual installation. It was indeed troublesome before to install pygame with homebrew (which was largely the fault of the SDL packages which were head-only back then), but now it goes quite smoothly.
You need to enter

    brew update
    brew tap homebrew/python

and after that it is simply a matter of doing

    brew install pygame

which also installs all dependencies.

**Comment by fladd** [comment]
That is good to know. I will try that out in the future again, thanks.

But let's get back to the core problem for a minute:

1) Did you try clearing the font cache in OS X?
2) How many fonts do you have installed? I once had Gimp scan over 10 min for fonts on OS X as well. How long did you let Expyriment scan for the fonts until you hit Ctrl-C?

**Comment by dschreij** [comment]
You're right, it works but does take a *very* long time (3-5 min) to load initially. Consecutive import attempts, after restarting the python interpreter, were a lot faster. I do not have a lot of extra fonts besides the ones installed on the system by default and the ones that Adobe might have added...

**Comment by fladd** [comment]
Good to hear it works!

Although the time is indeed very long. Adobe fonts I also have here. Is this on an older machine? Really strange. Mmh...you mentioned in the first post that there are alternative ways to make Pygame aware of system fonts? I would be really interested in learning about them. If there is an easy way to get rid of the initial long font scan, I am all for it!

**Comment by dschreij** [comment]
I am using a Late 2013 macbook, which is not that old I would say. Just by quickly Googling I find ttfquery, which is also used by pyopengl (http://pyopengl.sourceforge.net/pydoc/ttfquery.html). I also see PIL(low) has a method for querying system fonts. I have no idea how well these all work, but there are options. My guess is that if I experience these problems, then someone else will probably too, with longer waiting times indeed on slower computers. But luckily it is working and it is all a matter of convenience at the moment.

**Comment by fladd** [comment]
Thanks for checking! If you find the time, it would be great to know if those alternatives are indeed faster on your system. I will also need to see how to make Pygame aware of the system fonts, without having it scan for them.

**Comment by fladd** [comment]
I would very much like to add something like
```
    print("Initializing system fonts. This might take a couple of minutes...")
```
but I cannot figure out in what cases the font init takes so long. It seems related to not having a font cache, but I have no clue where to look for this font cache...
Any input is highly appreciated.

**Comment by lindemann09** [comment]
No idea, I am afraid that is highly specific to the OS.

Oliver


On 28.04.2016 15:50, Florian Krause wrote:
>
> I would very much like to add something like
>
> |print("Initializing system fonts. This might take a couple of 
> minutes...") |
>
> but I cannot figure out in what cases the font init takes so long. It 
> seems related to not having a font cache, but I have no clue where to 
> look for this font cache...
> Any input is highly appreciated.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/expyriment/expyriment/issues/69#issuecomment-215429663>
>

-- 
Dr. Oliver Lindemann
Division of Cognitive Science - University of Potsdam
http://www.cognitive-psychology.eu/lindemann

**Comment by dschreij** [comment]
I think you can print it anyway: if it doesn't take that long then then script will immediately continue and the user will probably not even notice that message has been printed (or thinks, wow my computer is fast, that didn't take long at all! ;) ). If it does take a long time, then the user is at least warned and aware of that the experiment isn't hanging but something time consuming is happening.

**Comment by fladd** [comment]
Hi Daniel,

always printing seems a bit too verbose, as it will be printed every single time Expyriment is imported.

However, one idea would be to only print it, when `pygame.sysfont.get_fonts()` returns `[None]`. Unfortunately, I cannot test this, as I cannot figure out a way to delete my font cache, such that Expyriment (well Pygame) needs to create it again, and takes so long. Do you have an idea how to get the system into that state again?

**Comment by fladd** [comment]
Oliver just had a better solution: We will now import Expyriment once, directly after installation. This ensures not only that the installation worked, but it also allows for us to print the message only at the point when the long waiting times might occur.

**Comment by fladd** [comment]
Since there is no post-install hook for wheels, I  went with this for now: https://github.com/expyriment/expyriment/issues/69#issuecomment-215717119
