### ISSUE TITLE
pyserial 3.0.1 is not compatible with Expyriment 0.8.0

### ISSUE THREAD

**Issue by lindemann09** [expyriment/expyriment#74]
All lab experiments with button-boxes do not work anymore after update or new installation of pyserial. That is a serious problem!
```
Traceback (most recent call last):
  File "/home/oliver/Dropbox/osf/spamint/experiment/WBPL16.py", line 139, in <module>
    voicekey = io.EventButtonBox(io.SerialPort("COM2", 115200, parity=None, stopbits = 1))
  File "/usr/local/lib/python2.7/dist-packages/expyriment/io/_serialport.py", line 88, in __init__
    if float(serial.VERSION) < 2.5:
ValueError: invalid literal for float(): 3.0.1
```

**Comment by fladd** [comment]
Yes, we need to change our code to be compatible with the new version. I see if I find some time this week. We should have this ready for 0.9.0.

**Comment by fladd** [comment]
https://github.com/expyriment/expyriment/pull/75 should fix this.

**Comment by lindemann09** [comment]
But that does not fix #74, right?

**Comment by lindemann09** [comment]
If fixed it: https://github.com/expyriment/expyriment/commit/963fba74ad9c0bcd3a5ab94cb5b7df8a913e5a30

**Comment by lindemann09** [comment]
If fixed it: 963fba7

**Comment by fladd** [comment]
Why not just:
```
if serial.VERSION < '2.5'
```

**Comment by lindemann09** [comment]
because e.g. "2.12" < "2.5" should be False and not True

Oliver


On 28.04.2016 15:49, Florian Krause wrote:
>
> Why not just:
>
> |if serial.VERSION < '2.5' |
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub 
> <https://github.com/expyriment/expyriment/issues/74#issuecomment-215429282>
>

-- 
Dr. Oliver Lindemann
Division of Cognitive Science - University of Potsdam
http://www.cognitive-psychology.eu/lindemann

**Comment by fladd** [comment]
Ah you are right. I wasn't aware that semantic versioning allows for two digit numbers.

A more elegant solution might be: http://stackoverflow.com/questions/11887762/how-to-compare-version-style-strings

**Comment by lindemann09** [comment]
Yes, can you change it?

Oliver

On 28.04.2016 16:14, Florian Krause wrote:
>
> Ah you are right. I wasn't aware that semantic versioning allows for 
> two digit numbers.
>
> A more elegant solution might be: 
> http://stackoverflow.com/questions/11887762/how-to-compare-version-style-strings
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub 
> <https://github.com/expyriment/expyriment/issues/74#issuecomment-215436745>
>

-- 
Dr. Oliver Lindemann
Division of Cognitive Science - University of Potsdam
http://www.cognitive-psychology.eu/lindemann
