### ISSUE TITLE
expyriment.io._parallel_port cannot be imported due to inpout32.dll error

### ISSUE THREAD

**Issue by smathot** [expyriment/expyriment#87]
Under Windows 7, using 64 bit Python 3.5, expyriment cannot be imported due to a problem with `inpout32.dll`. Apparently, even checking whether this dll exists can be dangerous:

![image](https://cloud.githubusercontent.com/assets/594936/17277087/d115ccaa-573a-11e6-8303-cb580ea2d7f8.png)

This completely breaks expyriment, which brings me to another point for which I will open a separate issue.

**Comment by lindemann09** [comment]
I pushed a first solution. I guess the error does not occur any more fixed. I can not test it right now, because I do not have a Windows machine.

**Comment by smathot** [comment]
Yes, it's fixed!
