### ISSUE TITLE
Permutating between participant factor regardless of another bw factor

### ISSUE THREAD

**Issue by mutlusun** [expyriment/expyriment#94]
Hello,

thanks for your great work! I really like how easy it is to structure my experiment with expyriment.
I'm not sure whether i missed it in the docs but I'm missing a function (or argument) to permutate a certain between participant factor without permuting over a second between participant factor. So, is there a possibility to permutate both factors independent of each other?

Regards

**Comment by fladd** [comment]
Mmh, can you give an example?

**Comment by mutlusun** [comment]
Here is a little example:
```python
import expyriment
import itertools

exp = expyriment.design.Experiment(name="test")
expyriment.control.set_develop_mode(True)
expyriment.control.initialize(exp)

exp.add_bws_factor("factor1", itertools.permutations([1, 2, 3]))
exp.add_bws_factor("factor2", itertools.permutations(["a", "b"]))

expyriment.control.start()
print(exp.get_permuted_bws_factor_condition("factor1"))
print(exp.get_permuted_bws_factor_condition("factor2"))
expyriment.control.end()
```
The result with expyriment is now:

participant id | factor1 | factor2
-----------------|----------|----------
1 | 1, 2, 3 | a, b
2 | 1, 2, 3 | b, a
3 | 1, 3, 2 | a, b
4 | 1, 3, 2 | b, a
5 | 3, 1, 2 | a, b
6 | 3, 1, 2 | b, a
7 | 3, 2, 1 | a, b
8 | 3, 2, 1 | b, a
9 | 2, 3, 1 | a, b
10 | 2, 3, 1 | b, a
11 | 2, 1, 3 | a, b
12 | 2, 1, 3 | b, a

I would like to get:

participant id | factor1 | factor2
-----------------|----------|----------
1 | 1, 2, 3 | a, b
2 | 1, 3, 2 | b, a
3 | 3, 1, 2 | a, b
4 | 3, 2, 1 | b, a
5 | 2, 3, 1 | a, b
6 | 2, 1, 3 | b, a

So, it's just I don't wanna have a latin square of both factors.
