### ISSUE TITLE
BlankScreen may need a massive amount of memory

### ISSUE THREAD

**Issue by mutlusun** [expyriment/expyriment#97]
Hello,

in my experiment I used to plot some text stimuli on top of a blank screen stimuli to show them together. I did this for every trial (around 300 or so ...). Then I noticed a big difference in memory usage between development and normal mode. Normal mode even crashed with pygame error: out of memory.

The BlankScreen stimuli may eat a lot of memory (depending on screen size) when used a lot of times. I don't know whether there is a nice solution for that problem, but maybe it would be nice to add a note to the documentation (actually I was a bit surprised that pygame is that bad in memory management -- it's actually only a one color rectangle). I circumvented this problem by using a plain Canvas stimuli with a smaller, fixed size and plotted on this one.

Greetings!

**Comment by lindemann09** [comment]
This not a bug and seems to be a question regarding the memory management in your experiment. (When do you preload and unload stimuli?). For any kind of user support, please conatct the new expyriment user forum and send code examples.  http://forum.cogsci.nl/categories/expyriment
